export const GAME_LOGOS = {
  PUBG: "https://b4uesports.com/wp-content/uploads/2025/10/pubgmoblielogob4uesports.webp",
  PUBG_SUBSCRIPTION: "https://b4uesports.com/wp-content/uploads/2025/10/pubgmoblielogob4uesports.webp",
  PUBGKR: "https://b4uesports.com/wp-content/uploads/2025/11/pubgkruc.png",
  MLBB: "https://b4uesports.com/wp-content/uploads/2025/10/mlbb-lgog.jpg",
  COC: "https://b4uesports.com/wp-content/uploads/2025/10/logo.985ee45d-removebg-preview.png",
  ROBUX: "https://b4uesports.com/wp-content/uploads/2025/12/1000019410-1.png",
  NEWSTATE: "https://b4uesports.com/wp-content/uploads/2025/12/1000020478-1.jpg",
  FREEFIRE: "https://b4uesports.com/wp-content/uploads/2025/12/1000020480.jpg",
  TIKTOK_COINS: "https://b4uesports.com/wp-content/uploads/2026/04/tiktok-coins-package.png-removebg-preview.png",
  TIKTOK_FOLLOWERS: "https://b4uesports.com/wp-content/uploads/2026/04/tiktokfollowers-removebg-preview.png",
  TIKTOK_VIEWS: "https://b4uesports.com/wp-content/uploads/2025/04/1000077314.png",
  YOUTUBE_SUBS: "https://b4uesports.com/wp-content/uploads/2025/04/1000077305.png",
  YOUTUBE_WATCHTIME: "https://b4uesports.com/wp-content/uploads/2026/03/youtube-wt.jpg",
  FACEBOOK: "https://b4uesports.com/wp-content/uploads/2026/04/facebooklogo.png",
  INSTAGRAM: "https://b4uesports.com/wp-content/uploads/2026/03/instagram-logo.jpg",
  NETFLIX: "https://b4uesports.com/wp-content/uploads/2026/04/netflix-logo-150x150-removebg-preview.png",
  CANVA: "https://b4uesports.com/wp-content/uploads/2026/04/canvanobackground-removebg-preview.png"
};

export const BRAND_LOGOS = {
  B4U: "https://b4uesports.com/wp-content/uploads/2025/04/cropped-Black_and_Blue_Simple_Creative_Illustrative_Dragons_E-Sport_Logo_20240720_103229_0000-removebg-preview.png", // TODO: Replace with your actual logo URL
  PI: "https://b4uesports.com/wp-content/uploads/2025/04/PI.jpg" // TODO: Replace with the URL of your downloaded official Pi Network logo
};

export const SOCIAL_LINKS = {
  FACEBOOK: "https://www.facebook.com/b4uesports",
  YOUTUBE: "https://youtube.com/@b4uesports",
  TIKTOK: "https://www.tiktok.com/b4uesports",
  INSTAGRAM: "https://www.instagram.com/b4uesports",
  LINKEDIN: "https://www.linkedin.com/company/b4uesports/"
};

export const CONTACT_INFO = {
  EMAIL: "info@b4uesports.com",
  PHONE: "+97517875099",
  WHATSAPP: "https://wa.me/+97517875099"
};

export const COUNTRIES = [
  { code: "AF", name: "Afghanistan", flag: "🇦🇫", phoneCode: "+93" },
  { code: "AL", name: "Albania", flag: "🇦🇱", phoneCode: "+355" },
  { code: "DZ", name: "Algeria", flag: "🇩🇿", phoneCode: "+213" },
  { code: "AD", name: "Andorra", flag: "🇦🇩", phoneCode: "+376" },
  { code: "AO", name: "Angola", flag: "🇦🇴", phoneCode: "+244" },
  { code: "AG", name: "Antigua and Barbuda", flag: "🇦🇬", phoneCode: "+1-268" },
  { code: "AR", name: "Argentina", flag: "🇦🇷", phoneCode: "+54" },
  { code: "AM", name: "Armenia", flag: "🇦🇲", phoneCode: "+374" },
  { code: "AU", name: "Australia", flag: "🇦🇺", phoneCode: "+61" },
  { code: "AT", name: "Austria", flag: "🇦🇹", phoneCode: "+43" },
  { code: "AZ", name: "Azerbaijan", flag: "🇦🇿", phoneCode: "+994" },
  { code: "BS", name: "Bahamas", flag: "🇧🇸", phoneCode: "+1-242" },
  { code: "BH", name: "Bahrain", flag: "🇧🇭", phoneCode: "+973" },
  { code: "BD", name: "Bangladesh", flag: "🇧🇩", phoneCode: "+880" },
  { code: "BB", name: "Barbados", flag: "🇧🇧", phoneCode: "+1-246" },
  { code: "BY", name: "Belarus", flag: "🇧🇾", phoneCode: "+375" },
  { code: "BE", name: "Belgium", flag: "🇧🇪", phoneCode: "+32" },
  { code: "BZ", name: "Belize", flag: "🇧🇿", phoneCode: "+501" },
  { code: "BJ", name: "Benin", flag: "🇧🇯", phoneCode: "+229" },
  { code: "BT", name: "Bhutan", flag: "🇧🇹", phoneCode: "+975" },
  { code: "BO", name: "Bolivia", flag: "🇧🇴", phoneCode: "+591" },
  { code: "BA", name: "Bosnia and Herzegovina", flag: "🇧🇦", phoneCode: "+387" },
  { code: "BW", name: "Botswana", flag: "🇧🇼", phoneCode: "+267" },
  { code: "BR", name: "Brazil", flag: "🇧🇷", phoneCode: "+55" },
  { code: "BN", name: "Brunei", flag: "🇧🇳", phoneCode: "+673" },
  { code: "BG", name: "Bulgaria", flag: "🇧🇬", phoneCode: "+359" },
  { code: "BF", name: "Burkina Faso", flag: "🇧🇫", phoneCode: "+226" },
  { code: "BI", name: "Burundi", flag: "🇧🇮", phoneCode: "+257" },
  { code: "CV", name: "Cabo Verde", flag: "🇨🇻", phoneCode: "+238" },
  { code: "KH", name: "Cambodia", flag: "🇰🇭", phoneCode: "+855" },
  { code: "CM", name: "Cameroon", flag: "🇨🇲", phoneCode: "+237" },
  { code: "CA", name: "Canada", flag: "🇨🇦", phoneCode: "+1" },
  { code: "CF", name: "Central African Republic", flag: "🇨🇫", phoneCode: "+236" },
  { code: "TD", name: "Chad", flag: "🇹🇩", phoneCode: "+235" },
  { code: "CL", name: "Chile", flag: "🇨🇱", phoneCode: "+56" },
  { code: "CN", name: "China", flag: "🇨🇳", phoneCode: "+86" },
  { code: "CO", name: "Colombia", flag: "🇨🇴", phoneCode: "+57" },
  { code: "KM", name: "Comoros", flag: "🇰🇲", phoneCode: "+269" },
  { code: "CG", name: "Congo", flag: "🇨🇬", phoneCode: "+242" },
  { code: "CD", name: "Congo (DRC)", flag: "🇨🇩", phoneCode: "+243" },
  { code: "CR", name: "Costa Rica", flag: "🇨🇷", phoneCode: "+506" },
  { code: "CI", name: "Côte d'Ivoire", flag: "🇨🇮", phoneCode: "+225" },
  { code: "HR", name: "Croatia", flag: "🇭🇷", phoneCode: "+385" },
  { code: "CU", name: "Cuba", flag: "🇨🇺", phoneCode: "+53" },
  { code: "CY", name: "Cyprus", flag: "🇨🇾", phoneCode: "+357" },
  { code: "CZ", name: "Czech Republic", flag: "🇨🇿", phoneCode: "+420" },
  { code: "DK", name: "Denmark", flag: "🇩🇰", phoneCode: "+45" },
  { code: "DJ", name: "Djibouti", flag: "🇩🇯", phoneCode: "+253" },
  { code: "DM", name: "Dominica", flag: "🇩🇲", phoneCode: "+1-767" },
  { code: "DO", name: "Dominican Republic", flag: "🇩🇴", phoneCode: "+1-809" },
  { code: "EC", name: "Ecuador", flag: "🇪🇨", phoneCode: "+593" },
  { code: "EG", name: "Egypt", flag: "🇪🇬", phoneCode: "+20" },
  { code: "SV", name: "El Salvador", flag: "🇸🇻", phoneCode: "+503" },
  { code: "GQ", name: "Equatorial Guinea", flag: "🇬🇶", phoneCode: "+240" },
  { code: "ER", name: "Eritrea", flag: "🇪🇷", phoneCode: "+291" },
  { code: "EE", name: "Estonia", flag: "🇪🇪", phoneCode: "+372" },
  { code: "SZ", name: "Eswatini", flag: "🇸🇿", phoneCode: "+268" },
  { code: "ET", name: "Ethiopia", flag: "🇪🇹", phoneCode: "+251" },
  { code: "FJ", name: "Fiji", flag: "🇫🇯", phoneCode: "+679" },
  { code: "FI", name: "Finland", flag: "🇫🇮", phoneCode: "+358" },
  { code: "FR", name: "France", flag: "🇫🇷", phoneCode: "+33" },
  { code: "GA", name: "Gabon", flag: "🇬🇦", phoneCode: "+241" },
  { code: "GM", name: "Gambia", flag: "🇬🇲", phoneCode: "+220" },
  { code: "GE", name: "Georgia", flag: "🇬🇪", phoneCode: "+995" },
  { code: "DE", name: "Germany", flag: "🇩🇪", phoneCode: "+49" },
  { code: "GH", name: "Ghana", flag: "🇬🇭", phoneCode: "+233" },
  { code: "GR", name: "Greece", flag: "🇬🇷", phoneCode: "+30" },
  { code: "GD", name: "Grenada", flag: "🇬🇩", phoneCode: "+1-473" },
  { code: "GT", name: "Guatemala", flag: "🇬🇹", phoneCode: "+502" },
  { code: "GN", name: "Guinea", flag: "🇬🇳", phoneCode: "+224" },
  { code: "GW", name: "Guinea-Bissau", flag: "🇬🇼", phoneCode: "+245" },
  { code: "GY", name: "Guyana", flag: "🇬🇾", phoneCode: "+592" },
  { code: "HT", name: "Haiti", flag: "🇭🇹", phoneCode: "+509" },
  { code: "HN", name: "Honduras", flag: "🇭🇳", phoneCode: "+504" },
  { code: "HU", name: "Hungary", flag: "🇭🇺", phoneCode: "+36" },
  { code: "IS", name: "Iceland", flag: "🇮🇸", phoneCode: "+354" },
  { code: "IN", name: "India", flag: "🇮🇳", phoneCode: "+91" },
  { code: "ID", name: "Indonesia", flag: "🇮🇩", phoneCode: "+62" },
  { code: "IR", name: "Iran", flag: "🇮🇷", phoneCode: "+98" },
  { code: "IQ", name: "Iraq", flag: "🇮🇶", phoneCode: "+964" },
  { code: "IE", name: "Ireland", flag: "🇮🇪", phoneCode: "+353" },
  { code: "IL", name: "Israel", flag: "🇮🇱", phoneCode: "+972" },
  { code: "IT", name: "Italy", flag: "🇮🇹", phoneCode: "+39" },
  { code: "JM", name: "Jamaica", flag: "🇯🇲", phoneCode: "+1-876" },
  { code: "JP", name: "Japan", flag: "🇯🇵", phoneCode: "+81" },
  { code: "JO", name: "Jordan", flag: "🇯🇴", phoneCode: "+962" },
  { code: "KZ", name: "Kazakhstan", flag: "🇰🇿", phoneCode: "+7" },
  { code: "KE", name: "Kenya", flag: "🇰🇪", phoneCode: "+254" },
  { code: "KI", name: "Kiribati", flag: "🇰🇮", phoneCode: "+686" },
  { code: "KP", name: "Korea (North)", flag: "🇰🇵", phoneCode: "+850" },
  { code: "KR", name: "Korea (South)", flag: "🇰🇷", phoneCode: "+82" },
  { code: "KW", name: "Kuwait", flag: "🇰🇼", phoneCode: "+965" },
  { code: "KG", name: "Kyrgyzstan", flag: "🇰🇬", phoneCode: "+996" },
  { code: "LA", name: "Laos", flag: "🇱🇦", phoneCode: "+856" },
  { code: "LV", name: "Latvia", flag: "🇱🇻", phoneCode: "+371" },
  { code: "LB", name: "Lebanon", flag: "🇱🇧", phoneCode: "+961" },
  { code: "LS", name: "Lesotho", flag: "🇱🇸", phoneCode: "+266" },
  { code: "LR", name: "Liberia", flag: "🇱🇷", phoneCode: "+231" },
  { code: "LY", name: "Libya", flag: "🇱🇾", phoneCode: "+218" },
  { code: "LI", name: "Liechtenstein", flag: "🇱🇮", phoneCode: "+423" },
  { code: "LT", name: "Lithuania", flag: "🇱🇹", phoneCode: "+370" },
  { code: "LU", name: "Luxembourg", flag: "🇱🇺", phoneCode: "+352" },
  { code: "MG", name: "Madagascar", flag: "🇲🇬", phoneCode: "+261" },
  { code: "MW", name: "Malawi", flag: "🇲🇼", phoneCode: "+265" },
  { code: "MY", name: "Malaysia", flag: "🇲🇾", phoneCode: "+60" },
  { code: "MV", name: "Maldives", flag: "🇲🇻", phoneCode: "+960" },
  { code: "ML", name: "Mali", flag: "🇲🇱", phoneCode: "+223" },
  { code: "MT", name: "Malta", flag: "🇲🇹", phoneCode: "+356" },
  { code: "MH", name: "Marshall Islands", flag: "🇲🇭", phoneCode: "+692" },
  { code: "MR", name: "Mauritania", flag: "🇲🇷", phoneCode: "+222" },
  { code: "MU", name: "Mauritius", flag: "🇲🇺", phoneCode: "+230" },
  { code: "MX", name: "Mexico", flag: "🇲🇽", phoneCode: "+52" },
  { code: "FM", name: "Micronesia", flag: "🇫🇲", phoneCode: "+691" },
  { code: "MD", name: "Moldova", flag: "🇲🇩", phoneCode: "+373" },
  { code: "MC", name: "Monaco", flag: "🇲🇨", phoneCode: "+377" },
  { code: "MN", name: "Mongolia", flag: "🇲🇳", phoneCode: "+976" },
  { code: "ME", name: "Montenegro", flag: "🇲🇪", phoneCode: "+382" },
  { code: "MA", name: "Morocco", flag: "🇲🇦", phoneCode: "+212" },
  { code: "MZ", name: "Mozambique", flag: "🇲🇿", phoneCode: "+258" },
  { code: "MM", name: "Myanmar", flag: "🇲🇲", phoneCode: "+95" },
  { code: "NA", name: "Namibia", flag: "🇳🇦", phoneCode: "+264" },
  { code: "NR", name: "Nauru", flag: "🇳🇷", phoneCode: "+674" },
  { code: "NP", name: "Nepal", flag: "🇳🇵", phoneCode: "+977" },
  { code: "NL", name: "Netherlands", flag: "🇳🇱", phoneCode: "+31" },
  { code: "NZ", name: "New Zealand", flag: "🇳🇿", phoneCode: "+64" },
  { code: "NI", name: "Nicaragua", flag: "🇳🇮", phoneCode: "+505" },
  { code: "NE", name: "Niger", flag: "🇳🇪", phoneCode: "+227" },
  { code: "NG", name: "Nigeria", flag: "🇳🇬", phoneCode: "+234" },
  { code: "MK", name: "North Macedonia", flag: "🇲🇰", phoneCode: "+389" },
  { code: "NO", name: "Norway", flag: "🇳🇴", phoneCode: "+47" },
  { code: "OM", name: "Oman", flag: "🇴🇲", phoneCode: "+968" },
  { code: "PK", name: "Pakistan", flag: "🇵🇰", phoneCode: "+92" },
  { code: "PW", name: "Palau", flag: "🇵🇼", phoneCode: "+680" },
  { code: "PA", name: "Panama", flag: "🇵🇦", phoneCode: "+507" },
  { code: "PG", name: "Papua New Guinea", flag: "🇵🇬", phoneCode: "+675" },
  { code: "PY", name: "Paraguay", flag: "🇵🇾", phoneCode: "+595" },
  { code: "PE", name: "Peru", flag: "🇵🇪", phoneCode: "+51" },
  { code: "PH", name: "Philippines", flag: "🇵🇭", phoneCode: "+63" },
  { code: "PL", name: "Poland", flag: "🇵🇱", phoneCode: "+48" },
  { code: "PT", name: "Portugal", flag: "🇵🇹", phoneCode: "+351" },
  { code: "QA", name: "Qatar", flag: "🇶🇦", phoneCode: "+974" },
  { code: "RO", name: "Romania", flag: "🇷🇴", phoneCode: "+40" },
  { code: "RU", name: "Russia", flag: "🇷🇺", phoneCode: "+7" },
  { code: "RW", name: "Rwanda", flag: "🇷🇼", phoneCode: "+250" },
  { code: "KN", name: "Saint Kitts and Nevis", flag: "🇰🇳", phoneCode: "+1-869" },
  { code: "LC", name: "Saint Lucia", flag: "🇱🇨", phoneCode: "+1-758" },
  { code: "VC", name: "Saint Vincent and the Grenadines", flag: "🇻🇨", phoneCode: "+1-784" },
  { code: "WS", name: "Samoa", flag: "🇼🇸", phoneCode: "+685" },
  { code: "SM", name: "San Marino", flag: "🇸🇲", phoneCode: "+378" },
  { code: "ST", name: "Sao Tome and Principe", flag: "🇸🇹", phoneCode: "+239" },
  { code: "SA", name: "Saudi Arabia", flag: "🇸🇦", phoneCode: "+966" },
  { code: "SN", name: "Senegal", flag: "🇸🇳", phoneCode: "+221" },
  { code: "RS", name: "Serbia", flag: "🇷🇸", phoneCode: "+381" },
  { code: "SC", name: "Seychelles", flag: "🇸🇨", phoneCode: "+248" },
  { code: "SL", name: "Sierra Leone", flag: "🇸🇱", phoneCode: "+232" },
  { code: "SG", name: "Singapore", flag: "🇸🇬", phoneCode: "+65" },
  { code: "SK", name: "Slovakia", flag: "🇸🇰", phoneCode: "+421" },
  { code: "SI", name: "Slovenia", flag: "🇸🇮", phoneCode: "+386" },
  { code: "SB", name: "Solomon Islands", flag: "🇸🇧", phoneCode: "+677" },
  { code: "SO", name: "Somalia", flag: "🇸🇴", phoneCode: "+252" },
  { code: "ZA", name: "South Africa", flag: "🇿🇦", phoneCode: "+27" },
  { code: "SS", name: "South Sudan", flag: "🇸🇸", phoneCode: "+211" },
  { code: "ES", name: "Spain", flag: "🇪🇸", phoneCode: "+34" },
  { code: "LK", name: "Sri Lanka", flag: "🇱🇰", phoneCode: "+94" },
  { code: "SD", name: "Sudan", flag: "🇸🇩", phoneCode: "+249" },
  { code: "SR", name: "Suriname", flag: "🇸🇷", phoneCode: "+597" },
  { code: "SE", name: "Sweden", flag: "🇸🇪", phoneCode: "+46" },
  { code: "CH", name: "Switzerland", flag: "🇨🇭", phoneCode: "+41" },
  { code: "SY", name: "Syria", flag: "🇸🇾", phoneCode: "+963" },
  { code: "TJ", name: "Tajikistan", flag: "🇹🇯", phoneCode: "+992" },
  { code: "TZ", name: "Tanzania", flag: "🇹🇿", phoneCode: "+255" },
  { code: "TH", name: "Thailand", flag: "🇹🇭", phoneCode: "+66" },
  { code: "TL", name: "Timor-Leste", flag: "🇹🇱", phoneCode: "+670" },
  { code: "TG", name: "Togo", flag: "🇹🇬", phoneCode: "+228" },
  { code: "TO", name: "Tonga", flag: "🇹🇴", phoneCode: "+676" },
  { code: "TT", name: "Trinidad and Tobago", flag: "🇹🇹", phoneCode: "+1-868" },
  { code: "TN", name: "Tunisia", flag: "🇹🇳", phoneCode: "+216" },
  { code: "TR", name: "Turkey", flag: "🇹🇷", phoneCode: "+90" },
  { code: "TM", name: "Turkmenistan", flag: "🇹🇲", phoneCode: "+993" },
  { code: "TV", name: "Tuvalu", flag: "🇹🇻", phoneCode: "+688" },
  { code: "UG", name: "Uganda", flag: "🇺🇬", phoneCode: "+256" },
  { code: "UA", name: "Ukraine", flag: "🇺🇦", phoneCode: "+380" },
  { code: "AE", name: "United Arab Emirates", flag: "🇦🇪", phoneCode: "+971" },
  { code: "GB", name: "United Kingdom", flag: "🇬🇧", phoneCode: "+44" },
  { code: "US", name: "United States", flag: "🇺🇸", phoneCode: "+1" },
  { code: "UY", name: "Uruguay", flag: "🇺🇾", phoneCode: "+598" },
  { code: "UZ", name: "Uzbekistan", flag: "🇺🇿", phoneCode: "+998" },
  { code: "VU", name: "Vanuatu", flag: "🇻🇺", phoneCode: "+678" },
  { code: "VA", name: "Vatican City", flag: "🇻🇦", phoneCode: "+39-06" },
  { code: "VE", name: "Venezuela", flag: "🇻🇪", phoneCode: "+58" },
  { code: "VN", name: "Vietnam", flag: "🇻🇳", phoneCode: "+84" },
  { code: "YE", name: "Yemen", flag: "🇾🇪", phoneCode: "+967" },
  { code: "ZM", name: "Zambia", flag: "🇿🇲", phoneCode: "+260" },
  { code: "ZW", name: "Zimbabwe", flag: "🇿🇼", phoneCode: "+263" }
];

export const LANGUAGES = [
  { code: "en", name: "English", flag: "🇺🇸", nativeName: "English" },
  { code: "dz", name: "Dzongkha", flag: "🇧🇹", nativeName: "རྫོང་ཁ" },
  { code: "hi", name: "Hindi", flag: "🇮🇳", nativeName: "हिन्दी" },
  { code: "bn", name: "Bengali", flag: "🇧🇩", nativeName: "বাংলা" },
  { code: "ne", name: "Nepali", flag: "🇳🇵", nativeName: "नेपाली" },
  { code: "id", name: "Indonesian", flag: "🇮🇩", nativeName: "Bahasa Indonesia" },
  { code: "tl", name: "Filipino", flag: "🇵🇭", nativeName: "Filipino" },
  { code: "zh", name: "Chinese", flag: "🇨🇳", nativeName: "中文" },
  { code: "ja", name: "Japanese", flag: "🇯🇵", nativeName: "日本語" },
  { code: "ko", name: "Korean", flag: "🇰🇷", nativeName: "한국어" },
  { code: "de", name: "German", flag: "🇩🇪", nativeName: "Deutsch" },
  { code: "fr", name: "French", flag: "🇫🇷", nativeName: "Français" },
  { code: "es", name: "Spanish", flag: "🇪🇸", nativeName: "Español" },
  { code: "pt", name: "Portuguese", flag: "🇧🇷", nativeName: "Português" },
  { code: "ar", name: "Arabic", flag: "🇸🇦", nativeName: "العربية" },
  { code: "ru", name: "Russian", flag: "🇷🇺", nativeName: "Русский" },
  { code: "tr", name: "Turkish", flag: "🇹🇷", nativeName: "Türkçe" },
  { code: "vi", name: "Vietnamese", flag: "🇻🇳", nativeName: "Tiếng Việt" },
  { code: "th", name: "Thai", flag: "🇹🇭", nativeName: "ภาษาไทย" },
  { code: "ms", name: "Malay", flag: "🇲🇾", nativeName: "Bahasa Melayu" },
  { code: "ur", name: "Urdu", flag: "🇵🇰", nativeName: "اردو" },
  { code: "fa", name: "Persian", flag: "🇮🇷", nativeName: "فارسی" },
  { code: "it", name: "Italian", flag: "🇮🇹", nativeName: "Italiano" },
  { code: "nl", name: "Dutch", flag: "🇳🇱", nativeName: "Nederlands" },
  { code: "pl", name: "Polish", flag: "🇵🇱", nativeName: "Polski" },
  { code: "uk", name: "Ukrainian", flag: "🇺🇦", nativeName: "Українська" },
  { code: "sv", name: "Swedish", flag: "🇸🇪", nativeName: "Svenska" },
  { code: "no", name: "Norwegian", flag: "🇳🇴", nativeName: "Norsk" },
  { code: "da", name: "Danish", flag: "🇩🇰", nativeName: "Dansk" },
  { code: "fi", name: "Finnish", flag: "🇫🇮", nativeName: "Suomi" },
  { code: "ro", name: "Romanian", flag: "🇷🇴", nativeName: "Română" },
  { code: "hu", name: "Hungarian", flag: "🇭🇺", nativeName: "Magyar" },
  { code: "cs", name: "Czech", flag: "🇨🇿", nativeName: "Čeština" },
  { code: "el", name: "Greek", flag: "🇬🇷", nativeName: "Ελληνικά" },
  { code: "he", name: "Hebrew", flag: "🇮🇱", nativeName: "עברית" },
  { code: "sw", name: "Swahili", flag: "🇰🇪", nativeName: "Kiswahili" },
  { code: "am", name: "Amharic", flag: "🇪🇹", nativeName: "አማርኛ" },
  { code: "my", name: "Burmese", flag: "🇲🇲", nativeName: "မြန်မာဘာသာ" },
  { code: "km", name: "Khmer", flag: "🇰🇭", nativeName: "ភាសាខ្មែរ" },
  { code: "si", name: "Sinhala", flag: "🇱🇰", nativeName: "සිංහල" },
  { code: "ta", name: "Tamil", flag: "🇮🇳", nativeName: "தமிழ்" },
  { code: "te", name: "Telugu", flag: "🇮🇳", nativeName: "తెలుగు" },
  { code: "ml", name: "Malayalam", flag: "🇮🇳", nativeName: "മലയാളം" },
  { code: "mn", name: "Mongolian", flag: "🇲🇳", nativeName: "Монгол" },
  { code: "kk", name: "Kazakh", flag: "🇰🇿", nativeName: "Қазақша" },
];

export const PACKAGE_IMAGES = {
  PUBG: "", // Updated to use the new PUBG UC image for all packages
  PUBGKR: "https://b4uesports.com/wp-content/uploads/2025/11/kr-uc.png",
  MLBB: "",
  COC: "",
  ROBUX: "",
  NEWSTATE: "",
  FREEFIRE: "https://b4uesports.com/wp-content/uploads/2025/04/1000048821.png",
  TIKTOK_COINS: "/images/tiktok-coins-package.png",
  TIKTOK_FOLLOWERS: "",
  TIKTOK_VIEWS: "",
  YOUTUBE_SUBS: "",
  YOUTUBE_WATCHTIME: "",
  FACEBOOK: "https://b4uesports.com/wp-content/uploads/2026/04/facebooklogo.png",
  INSTAGRAM: "https://b4uesports.com/wp-content/uploads/2026/03/instagram-followers.jpg",
  NETFLIX: "https://b4uesports.com/wp-content/uploads/2026/04/netflix-logo-150x150-removebg-preview.png",
  CANVA: "https://b4uesports.com/wp-content/uploads/2026/04/canvanobackground-removebg-preview.png"
};

export const DEFAULT_PACKAGES = {
  PUBG: [
    { amount: 0.06, usdtValue: 0.001 },
    { amount: 60, usdtValue: 1.5 },
    { amount: 325, usdtValue: 6.5 },
    { amount: 660, usdtValue: 12.0 },
    { amount: 1800, usdtValue: 25.0 },
    { amount: 3850, usdtValue: 49.0 },
    { amount: 8100, usdtValue: 96.0 },
    { amount: 16200, usdtValue: 186.0 },
    { amount: 24300, usdtValue: 278.0 },
    { amount: 32400, usdtValue: 369.0 },
    { amount: 40500, usdtValue: 459.0 },
  ],
  PUBGKR: [
    { amount: 60, usdtValue: 3.31 },
    { amount: 190, usdtValue: 5.31 },
    { amount: 660, usdtValue: 11.31 },
    { amount: 1800, usdtValue: 25.31 },
    { amount: 3850, usdtValue: 42.31 },
    { amount: 8100, usdtValue: 81.31 },
  ],
  MLBB: [
    { amount: 56, usdtValue: 3.0 },
    { amount: 278, usdtValue: 6.0 },
    { amount: 571, usdtValue: 11.0 },
    { amount: 1783, usdtValue: 33.0 },
    { amount: 3005, usdtValue: 52.0 },
    { amount: 6012, usdtValue: 99.0 },
    { amount: 12000, usdtValue: 200.0 },
  ],
  COC: [
    { amount: 1, usdtValue: 9.0 } // Gold Pass package with 9 USDT value
  ]
};
