import * as schema from "../shared/schema.js";
import { db, isMockDatabase } from "./db.js";
import { eq, desc, and, count, sum, sql, gte, notInArray } from "drizzle-orm";
import { randomUUID } from "crypto";
import { dedupePackages } from "./package-deduplication.js";
import type { 
  User, 
  InsertUser,
  Package,
  InsertPackage,
  Transaction,
  InsertTransaction,
  Admin,
  InsertAdmin,
  PiPriceHistory,
  // Chat message types removed to avoid compile errors when chat tables are deleted
  Tournament,
  InsertTournament,
  TournamentRegistration,
  InsertTournamentRegistration,
  TournamentTeam,
  InsertTournamentTeam,
  TournamentTeamMember,
  TournamentCheckIn,
  TournamentMatch,
  InsertTournamentMatch,
  TournamentMatchParticipant,
  InsertTournamentMatchParticipant,
  TournamentMatchResult,
  InsertTournamentMatchResult,
  TournamentLeaderboard,
  InsertTournamentLeaderboard,
  TournamentPayment,
  InsertTournamentPayment,
  TournamentNotification,
  InsertTournamentNotification,
  TournamentPrizeDistribution,
  InsertTournamentPrizeDistribution
} from "../shared/schema.js";

// Helper function to remove id from insert objects since it's generated by the database
type WithoutId<T> = Omit<T, 'id'>;

// All data is now stored in the real database

function isTransientDatabaseConnectionError(error: unknown): boolean {
  const message = error instanceof Error ? error.message : String(error);
  return /timeout exceeded|ECONN|ENOTFOUND|ETIMEDOUT|connection terminated|Connection terminated|database.*connect/i.test(message);
}

function delay(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function runWithConnectionRetry<T>(operationName: string, operation: () => Promise<T>): Promise<T> {
  let lastError: unknown;
  for (let attempt = 0; attempt < 2; attempt += 1) {
    try {
      return await operation();
    } catch (error: any) {
      const isPoolExhaustion = error?.code === 'EMAXCONNSESSION' || /max clients|pool_size|session mode/i.test(String(error?.message || error));
      lastError = error;
      if (!isPoolExhaustion || attempt === 1) {
        throw error;
      }

      console.warn(`Database pool exhausted while running ${operationName}; retrying once after a short delay...`, error?.message || error);
      await delay(750);
    }
  }

  throw lastError;
}

export interface IStorage {
  // Users
  getUser(id: string): Promise<User | undefined>;
  getUserByPiUID(piUID: string): Promise<User | undefined>;
  getUserByEmail(email: string): Promise<User | undefined>;
  createUser(user: InsertUser): Promise<User>;
  updateUser(id: string, user: Partial<User>): Promise<User | undefined>;
  addUserTokens(id: string, amount: number): Promise<User | undefined>;
  updateUserLastLogin(id: string): Promise<void>;
  findUserById(id: string): Promise<User | undefined>;
  createRedemptionRecord(userId: string, tokensRedeemed: number, piAmount: number, walletAddress: string): Promise<string>;
  
  // Packages
  getPackages(): Promise<Package[]>;
  getActivePackages(): Promise<Package[]>;
  getPackage(id: string): Promise<Package | undefined>;
  createPackage(pkg: InsertPackage): Promise<Package>;
  updatePackage(id: string, pkg: Partial<Package>): Promise<Package | undefined>;
  
  // Transactions
  getTransaction(id: string): Promise<Transaction | undefined>;
  getTransactionByPaymentId(paymentId: string): Promise<Transaction | undefined>;
  getUserTransactions(userId: string): Promise<Transaction[]>;
  createTransaction(transaction: InsertTransaction): Promise<Transaction>;
  updateTransaction(id: string, transaction: Partial<Transaction>): Promise<Transaction | undefined>;
  getAllTransactions(): Promise<(Transaction & { user: User; package: Package })[]>;
  
  // Admins
  getAdminByUsername(username: string): Promise<Admin | undefined>;
  getAllActiveAdmins(): Promise<Admin[]>;
  createAdmin(admin: InsertAdmin): Promise<Admin>;
  updateAdminLastLogin(id: string): Promise<void>;
  
  // Pi Price History
  savePiPrice(price: number): Promise<PiPriceHistory>;
  getLatestPiPrice(): Promise<PiPriceHistory | undefined>;
  
  // Analytics
  getAnalytics(): Promise<{
    totalUsers: number;
    totalTransactions: number;
    totalRevenue: number;
    successRate: number;
    lifetimeLoggedInUsers: number; // Add this new field
  }>;
  
  // Referral codes
  getUserByReferralCode(referralCode: string): Promise<User | undefined>;
  getUserReferralCode(userId: string): Promise<string | undefined>;
  rewardReferrer(referredUserId: string): Promise<void>;
  
  // Email functions
  getAllUserEmails(): Promise<string[]>;
  getAllAdminEmails(): Promise<string[]>;
  
  // Chat Messages (disabled) - use `any` to avoid type errors after removing chat schema
  saveChatMessage(message: any): Promise<any>;
  getChatMessagesBySession(sessionId: string, limit?: number): Promise<any[]>;
  getUserChatHistory(userId: string, limit?: number): Promise<any[]>;

  // Tournaments
  getTournaments(status?: string): Promise<Tournament[]>;
  getTournament(id: string): Promise<Tournament | undefined>;
  getTournamentBySlug(slug: string): Promise<Tournament | undefined>;
  createTournament(tournament: InsertTournament): Promise<Tournament>;
  updateTournament(id: string, tournament: Partial<Tournament>): Promise<Tournament | undefined>;
  createTournamentPrizeDistribution(prize: InsertTournamentPrizeDistribution): Promise<TournamentPrizeDistribution>;
  getTournamentPrizeDistributions(tournamentId: string): Promise<TournamentPrizeDistribution[]>;
  registerForTournament(registration: InsertTournamentRegistration): Promise<TournamentRegistration>;
  getTournamentRegistrations(tournamentId: string): Promise<TournamentRegistration[]>;
  getTournamentRegistrationsLite(tournamentId: string): Promise<Pick<TournamentRegistration, 'id' | 'teamId' | 'status' | 'paymentStatus' | 'metadata'>[]>;
  getUserTournamentRegistrations(userId: string): Promise<TournamentRegistration[]>;
  getTournamentRegistrationByPaymentId(paymentId: string): Promise<TournamentRegistration | undefined>;
  updateTournamentRegistration(id: string, registration: Partial<TournamentRegistration>): Promise<TournamentRegistration | undefined>;
  createTournamentTeam(team: InsertTournamentTeam): Promise<TournamentTeam>;
  addTournamentTeamMember(teamId: string, userId: string, role?: string): Promise<TournamentTeamMember>;
  getTournamentTeams(tournamentId: string): Promise<TournamentTeam[]>;
  deleteTournamentMatchResults(matchId: string): Promise<void>;
  getTournamentMatchResults(matchId: string): Promise<TournamentMatchResult[]>;
  rebuildTournamentLeaderboard(tournamentId: string): Promise<TournamentLeaderboard[]>;
  checkInTournamentParticipant(tournamentId: string, userId: string, teamId?: string): Promise<TournamentCheckIn>;
  createTournamentPayment(payment: InsertTournamentPayment): Promise<TournamentPayment>;
  updateTournamentPayment(id: string, payment: Partial<TournamentPayment>): Promise<TournamentPayment | undefined>;
  createTournamentLobby(lobbyData: { tournamentId: string; matchId?: string; name: string; mapName?: string; roomCode?: string; roomPassword?: string; status?: string; capacity?: number }): Promise<any>;
  updateTournamentLobby(lobbyId: string, updateData: Record<string, any>): Promise<any>;
  getTournamentLobbies(tournamentId: string): Promise<any[]>;
  getTournamentMatch(matchId: string): Promise<TournamentMatch | undefined>;
  deleteTournamentLobby(lobbyId: string): Promise<any>;
  createTournamentMatch(match: InsertTournamentMatch): Promise<TournamentMatch>;
  updateTournamentMatch(id: string, match: Partial<TournamentMatch>): Promise<TournamentMatch | undefined>;
  deleteTournamentMatch(id: string): Promise<TournamentMatch | undefined>;
  addTournamentMatchParticipant(participant: InsertTournamentMatchParticipant): Promise<TournamentMatchParticipant>;
  submitTournamentMatchResult(result: InsertTournamentMatchResult): Promise<TournamentMatchResult>;
  getTournamentMatches(tournamentId: string): Promise<TournamentMatch[]>;
  upsertTournamentLeaderboardEntry(entry: InsertTournamentLeaderboard): Promise<TournamentLeaderboard>;
  getTournamentLeaderboard(tournamentId: string): Promise<TournamentLeaderboard[]>;
  createTournamentNotification(notification: InsertTournamentNotification): Promise<TournamentNotification>;
  getUserTournamentNotifications(userId: string): Promise<TournamentNotification[]>;
}

export class DatabaseStorage implements IStorage {
  async getUser(id: string): Promise<User | undefined> {
    if (!db) {
      throw new Error('Database not initialized');
    }
    
    try {
      const [result] = await db.select().from(schema.users).where(eq(schema.users.id, id));
      if (result) {
        console.log('Found user in database: YES, Tokens:', result.tokens || 0);
      } else {
        console.log('Found user in database: NO');
      }
      return result || undefined;
    } catch (error) {
      console.error('Error fetching user by ID:', id, error);
      return undefined;
    }
  }

  async getUserByPiUID(piUID: string): Promise<User | undefined> {
    if (!db) {
      throw new Error('Database not initialized');
    }
    
    try {
      return await runWithConnectionRetry('getUserByPiUID', async () => {
        const [result] = await db.select().from(schema.users).where(eq(schema.users.piUID, piUID));
        return result || undefined;
      });
    } catch (error: any) {
      // If the column doesn't exist yet (migration pending), run it automatically
      if (error.code === '42703' && error.message?.includes('last_daily_claim_at')) {
        console.warn('⚠️  last_daily_claim_at column missing — running auto-migration...');
        try {
          await db.execute(sql`ALTER TABLE app_users ADD COLUMN IF NOT EXISTS last_daily_claim_at TIMESTAMP`);
          console.log('✅ last_daily_claim_at column added automatically');
          const [retryResult] = await db.select().from(schema.users).where(eq(schema.users.piUID, piUID));
          return retryResult || undefined;
        } catch (migrationError) {
          console.error('Auto-migration failed:', migrationError);
        }
      }
      console.error('Error fetching user by Pi UID:', piUID, error);
      return undefined;
    }
  }

  async getUserByEmail(email: string): Promise<User | undefined> {
    if (!db) {
      throw new Error('Database not initialized');
    }
    
    try {
      const [result] = await db
        .select()
        .from(schema.users)
        .where(eq(schema.users.email, email.trim().toLowerCase()));
      return result || undefined;
    } catch (error) {
      console.error('Error fetching user by email:', email, error);
      return undefined;
    }
  }

  async createUser(insertUser: InsertUser): Promise<User> {
    if (!db) {
      throw new Error('Database not initialized');
    }
    
    try {
      return await runWithConnectionRetry('createUser', async () => {
        const id = randomUUID();
        // @ts-ignore - Drizzle ORM types are complex with JSON fields
        const [result] = await db.insert(schema.users).values({ 
          id, 
          piUID: insertUser.piUID,
          username: insertUser.username,
          email: insertUser.email,
          phone: insertUser.phone,
          country: insertUser.country ?? 'Bhutan',
          language: insertUser.language ?? 'en',
          walletAddress: insertUser.walletAddress ?? null,
          gameAccounts: insertUser.gameAccounts ? insertUser.gameAccounts as User['gameAccounts'] : null,
          socialAccounts: insertUser.socialAccounts ? insertUser.socialAccounts as User['socialAccounts'] : null,
          referralCode: insertUser.referralCode ?? null, // Let database generate if null
          referredBy: insertUser.referredBy ?? null, // Add referredBy field
          passphrase: insertUser.passphrase ?? null,
          isActive: insertUser.isActive ?? true,
          isProfileVerified: insertUser.isProfileVerified ?? false,
          tokens: insertUser.tokens ?? 0, // Add tokens field
          createdAt: new Date(),
          updatedAt: new Date(),
        }).returning();
        return result;
      });
    } catch (error: any) {
      // Handle missing columns gracefully (database migration not applied yet)
      if (error.code === '42703' && error.message.includes('successful_purchases_count')) {
        console.warn('⚠️ Database migration not applied yet, creating user without reward tracking columns');
        
        // Retry without the new columns
        const id = randomUUID();
        const [retryResult] = await db.insert(schema.users).values({ 
          id, 
          piUID: insertUser.piUID,
          username: insertUser.username,
          email: insertUser.email,
          phone: insertUser.phone,
          country: insertUser.country ?? 'Bhutan',
          language: insertUser.language ?? 'en',
          walletAddress: insertUser.walletAddress ?? null,
          gameAccounts: insertUser.gameAccounts ? insertUser.gameAccounts as User['gameAccounts'] : null,
          referralCode: insertUser.referralCode ?? null,
          referredBy: insertUser.referredBy ?? null,
          passphrase: insertUser.passphrase ?? null,
          isActive: insertUser.isActive ?? true,
          isProfileVerified: insertUser.isProfileVerified ?? false,
          tokens: insertUser.tokens ?? 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        }).returning();
        
        return retryResult;
      }

      // Handle missing last_daily_claim_at column — auto-migrate and retry
      if (error.code === '42703' && error.message.includes('last_daily_claim_at')) {
        console.warn('⚠️ last_daily_claim_at column missing — running auto-migration and retrying createUser...');
        try {
          await db.execute(sql`ALTER TABLE app_users ADD COLUMN IF NOT EXISTS last_daily_claim_at TIMESTAMP`);
          console.log('✅ last_daily_claim_at column added automatically');
          // Retry the original insert
          const id2 = randomUUID();
          // @ts-ignore
          const [retryResult2] = await db.insert(schema.users).values({
            id: id2,
            piUID: insertUser.piUID,
            username: insertUser.username,
            email: insertUser.email,
            phone: insertUser.phone,
            country: insertUser.country ?? 'Bhutan',
            language: insertUser.language ?? 'en',
            walletAddress: insertUser.walletAddress ?? null,
            gameAccounts: insertUser.gameAccounts ? insertUser.gameAccounts as User['gameAccounts'] : null,
            socialAccounts: insertUser.socialAccounts ? insertUser.socialAccounts as User['socialAccounts'] : null,
            referralCode: insertUser.referralCode ?? null,
            referredBy: insertUser.referredBy ?? null,
            passphrase: insertUser.passphrase ?? null,
            isActive: insertUser.isActive ?? true,
            isProfileVerified: insertUser.isProfileVerified ?? false,
            tokens: insertUser.tokens ?? 0,
            createdAt: new Date(),
            updatedAt: new Date(),
          }).returning();
          return retryResult2;
        } catch (migrationError) {
          console.error('Auto-migration + retry failed:', migrationError);
        }
      }
      
      console.error('Error creating user:', error);
      throw error; // Re-throw to be handled by caller
    }
  }

  async updateUser(id: string, userData: Partial<User>): Promise<User | undefined> {
    if (!db) {
      throw new Error('Database not initialized');
    }
    
    try {
      // Handle gameAccounts specifically for JSONB field
      let updateData = { ...userData };
      if (userData.gameAccounts) {
        // Ensure gameAccounts is properly formatted for JSONB
        updateData = {
          ...updateData,
          gameAccounts: userData.gameAccounts as any
        };
      }
      if (userData.socialAccounts) {
        // Ensure socialAccounts is properly formatted for JSONB
        updateData = {
          ...updateData,
          socialAccounts: userData.socialAccounts as any
        };
      }
      
      // @ts-ignore - Drizzle ORM types are complex with JSON fields
      const [result] = await db
        .update(schema.users)
        .set({ ...updateData, updatedAt: new Date() })
        .where(eq(schema.users.id, id))
        .returning();
      return result || undefined;
    } catch (error) {
      console.error('Error updating user:', id, error);
      throw error; // Re-throw to be handled by caller
    }
  }
  
  async addUserTokens(id: string, amount: number): Promise<User | undefined> {
    if (!db) {
      throw new Error('Database not initialized');
    }
    
    try {
      console.log(`Adding ${amount} tokens to user ${id}`);
      // @ts-ignore - Drizzle ORM types are complex with JSON fields
      const [result] = await db
        .update(schema.users)
        .set({ 
          tokens: sql`${schema.users.tokens} + ${amount}`,
          updatedAt: new Date() 
        })
        .where(eq(schema.users.id, id))
        .returning();
      console.log(`Tokens added successfully. New token count: ${result?.tokens || 0}`);
      return result || undefined;
    } catch (error) {
      console.error('Database error while adding tokens:', error);
      throw new Error(`Failed to update tokens in database: ${(error as Error).message}`);
    }
  }

  async findUserById(id: string): Promise<User | undefined> {
    if (!db) {
      throw new Error('Database not initialized');
    }
    
    try {
      const [user] = await db
        .select()
        .from(schema.users)
        .where(eq(schema.users.id, id))
        .limit(1);
      
      return user || undefined;
    } catch (error) {
      console.error('Database error while finding user by ID:', error);
      throw new Error(`Failed to find user by ID: ${(error as Error).message}`);
    }
  }

  async createRedemptionRecord(userId: string, tokensRedeemed: number, piAmount: number, walletAddress: string): Promise<string> {
    if (!db) {
      throw new Error('Database not initialized');
    }
    
    try {
      // For now, we'll just return a mock redemption ID
      // In a real implementation, you would create a redemption_records table
      const redemptionId = `redemption_${Date.now()}_${userId}`;
      console.log('Created redemption record:', redemptionId);
      return redemptionId;
    } catch (error) {
      console.error('Database error while creating redemption record:', error);
      throw new Error(`Failed to create redemption record: ${(error as Error).message}`);
    }
  }

  async getPackages(): Promise<Package[]> {
    if (!db) {
      throw new Error('Database not initialized');
    }
    
    const packages = await db
      .select({
        id: schema.packages.id,
        game: schema.packages.game,
        name: schema.packages.name,
        inGameAmount: schema.packages.inGameAmount,
        usdtValue: schema.packages.usdtValue,
        image: schema.packages.image,
        isActive: schema.packages.isActive,
        createdAt: schema.packages.createdAt,
        updatedAt: schema.packages.updatedAt,
      })
      .from(schema.packages)
      .orderBy(schema.packages.game, schema.packages.usdtValue);

    return dedupePackages(packages as any);
  }

  async getActivePackages(): Promise<Package[]> {
    if (!db) {
      console.error('Storage Service: Database not initialized');
      throw new Error('Database not initialized');
    }
    
    console.log('Storage Service: Fetching active packages from database');
    const packages = await db
      .select({
        id: schema.packages.id,
        game: schema.packages.game,
        name: schema.packages.name,
        inGameAmount: schema.packages.inGameAmount,
        usdtValue: schema.packages.usdtValue,
        image: schema.packages.image,
        isActive: schema.packages.isActive,
        createdAt: schema.packages.createdAt,
        updatedAt: schema.packages.updatedAt,
      })
      .from(schema.packages)
      .where(eq(schema.packages.isActive, true))
      .orderBy(schema.packages.game, schema.packages.usdtValue);
      
    const dedupedPackages = dedupePackages(packages as any).filter((pkg: Package) => pkg.isActive);
    console.log('Storage Service: Returning', dedupedPackages.length, 'packages from database');
    return dedupedPackages;
  }

  async getPackage(id: string): Promise<Package | undefined> {
    if (!db) {
      throw new Error('Database not initialized');
    }
    
    const [result] = await db.select().from(schema.packages).where(eq(schema.packages.id, id));
    return result || undefined;
  }

  async createPackage(insertPackage: InsertPackage): Promise<Package> {
    if (!db) {
      throw new Error('Database not initialized');
    }
    
    const id = randomUUID();
    // @ts-ignore - Drizzle ORM types are complex with JSON fields
    const [result] = await db.insert(schema.packages).values({ 
      id, 
      game: insertPackage.game,
      name: insertPackage.name,
      inGameAmount: insertPackage.inGameAmount,
      usdtValue: insertPackage.usdtValue,
      image: insertPackage.image,
      isActive: insertPackage.isActive ?? true,
      createdAt: new Date(),
      updatedAt: new Date(),
    }).returning();
    return result;
  }

  async updatePackage(id: string, packageData: Partial<Package>): Promise<Package | undefined> {
    if (!db) {
      throw new Error('Database not initialized');
    }
    
    // @ts-ignore - Drizzle ORM types are complex with JSON fields
    const [result] = await db
      .update(schema.packages)
      .set({ ...packageData, updatedAt: new Date() })
      .where(eq(schema.packages.id, id))
      .returning();
    return result || undefined;
  }

  async getTransaction(id: string): Promise<Transaction | undefined> {
    if (!db) {
      throw new Error('Database not initialized');
    }
    
    const [result] = await db.select().from(schema.transactions).where(eq(schema.transactions.id, id));
    return result || undefined;
  }

  async getTransactionWithUserAndPackage(id: string): Promise<any> {
    if (!db) {
      throw new Error('Database not initialized');
    }
    
    const result = await db
      .select({
        id: schema.transactions.id,
        userId: schema.transactions.userId,
        packageId: schema.transactions.packageId,
        paymentId: schema.transactions.paymentId,
        txid: schema.transactions.txid,
        piAmount: schema.transactions.piAmount,
        usdAmount: schema.transactions.usdAmount,
        piPriceAtTime: schema.transactions.piPriceAtTime,
        status: schema.transactions.status,
        failureReason: schema.transactions.failureReason,
        successReason: schema.transactions.successReason,
        gameAccount: schema.transactions.gameAccount,
        metadata: schema.transactions.metadata,
        emailSent: schema.transactions.emailSent,
        createdAt: schema.transactions.createdAt,
        updatedAt: schema.transactions.updatedAt,
        user_email: schema.users.email,
        user_username: schema.users.username,
        user_phone: schema.users.phone,
        user_wallet_address: schema.users.walletAddress,
        user_game_accounts: schema.users.gameAccounts,
        user_social_accounts: schema.users.socialAccounts,
        package_name: schema.packages.name,
        package_game: schema.packages.game,
        package_in_game_amount: schema.packages.inGameAmount,
      })
      .from(schema.transactions)
      .leftJoin(schema.users, eq(schema.transactions.userId, schema.users.id))
      .leftJoin(schema.packages, eq(schema.transactions.packageId, schema.packages.id))
      .where(eq(schema.transactions.id, id));
      
    return result.length > 0 ? result[0] : null;
  }

  async getTransactionByPaymentId(paymentId: string): Promise<Transaction | undefined> {
    if (!db) {
      throw new Error('Database not initialized');
    }
    
    const [result] = await db
      .select()
      .from(schema.transactions)
      .where(eq(schema.transactions.paymentId, paymentId));
    return result || undefined;
  }

  async getUserTransactions(userId: string, filterStatus?: string, sortBy?: 'date' | 'amount'): Promise<Transaction[]> {
    const startTime = Date.now();
    const requestId = Math.random().toString(36).substring(2, 15);
    
    try {
      if (!db) {
        const error = new Error('Database not initialized');
        console.error(`[${requestId}] getUserTransactions: Database not initialized`, {
          userId,
          error: error.message,
          stack: error.stack,
          duration: Date.now() - startTime
        });
        throw error;
      }

      if (!userId || typeof userId !== 'string') {
        const error = new Error('Invalid userId passed to getUserTransactions');
        console.error(`[${requestId}] getUserTransactions: Invalid userId`, {
          userId,
          filterStatus,
          sortBy,
          duration: Date.now() - startTime
        });
        throw error;
      }
      
      // Add logging to see what's happening
      console.log(`[${requestId}] getUserTransactions called with userId:`, userId, { filterStatus, sortBy });
      
      let result: Transaction[] = [];
      const maxAttempts = 2;

      for (let attempt = 1; attempt <= maxAttempts; attempt++) {
        try {
          // Build conditions array ensuring userId is ALWAYS strictly enforced
          const conditions: any[] = [eq(schema.transactions.userId, userId)];
          
          if (filterStatus && filterStatus !== 'all') {
            if (filterStatus === 'completed') {
              conditions.push(sql`lower(${schema.transactions.status}) IN ('completed', 'approved')`);
            } else {
              conditions.push(eq(schema.transactions.status, filterStatus));
            }
          }
          
          let query: any = db
            .select()
            .from(schema.transactions)
            .where(and(...conditions));
          
          if (sortBy === 'amount') {
            query = query.orderBy(desc(schema.transactions.piAmount));
          } else {
            query = query.orderBy(desc(schema.transactions.createdAt));
          }
          
          result = await query;
          break;
        } catch (queryError) {
          const shouldRetry = attempt < maxAttempts && isTransientDatabaseConnectionError(queryError);
          if (!shouldRetry) {
            throw queryError;
          }

          console.warn(`[${requestId}] getUserTransactions transient database error, retrying`, {
            userId,
            attempt,
            nextAttempt: attempt + 1,
            error: (queryError as Error).message,
            duration: Date.now() - startTime
          });
          await delay(250);
        }
      }
      
      console.log(`[${requestId}] getUserTransactions result length:`, result.length, {
        userId,
        duration: Date.now() - startTime
      });
      
      if (result.length > 0) {
        console.log(`[${requestId}] First transaction:`, {
          id: result[0].id,
          status: result[0].status,
          createdAt: result[0].createdAt,
          duration: Date.now() - startTime
        });
      }
      
      return result;
    } catch (error) {
      const errorResponse = {
        message: 'Error in getUserTransactions',
        error: (error as Error).message,
        stack: process.env.NODE_ENV === 'development' ? (error as Error).stack : undefined,
        userId,
        filterStatus,
        sortBy,
        requestId,
        duration: Date.now() - startTime
      };
      
      console.error(`[${requestId}] Error in getUserTransactions:`, errorResponse);
      throw error;
    }
  }

  async createTransaction(insertTransaction: InsertTransaction): Promise<Transaction> {
    if (!db) {
      throw new Error('Database not initialized');
    }
    
    const id = randomUUID();
    // @ts-ignore - Drizzle ORM types are complex with JSON fields
    const [result] = await db.insert(schema.transactions).values({ 
      id, 
      userId: insertTransaction.userId,
      packageId: insertTransaction.packageId,
      paymentId: insertTransaction.paymentId,
      txid: insertTransaction.txid ?? null,
      piAmount: insertTransaction.piAmount,
      usdAmount: insertTransaction.usdAmount,
      piPriceAtTime: insertTransaction.piPriceAtTime,
      status: insertTransaction.status ?? 'pending',
      gameAccount: insertTransaction.gameAccount ? insertTransaction.gameAccount as Transaction['gameAccount'] : { ign: undefined, uid: undefined, userId: undefined, zoneId: undefined },
      metadata: insertTransaction.metadata ?? null,
      emailSent: insertTransaction.emailSent ?? false,
      paymentType: insertTransaction.paymentType ?? 'TOKEN_PURCHASE',
      tournamentId: insertTransaction.tournamentId ?? null,
      createdAt: new Date(),
      updatedAt: new Date(),
    }).returning();
    return result;
  }

  async updateTransaction(id: string, transactionData: Partial<Transaction>): Promise<Transaction | undefined> {
    if (!db) {
      throw new Error('Database not initialized');
    }
    
    // @ts-ignore - Drizzle ORM types are complex with JSON fields
    const [result] = await db
      .update(schema.transactions)
      .set({ ...transactionData, updatedAt: new Date() })
      .where(eq(schema.transactions.id, id))
      .returning();
    return result || undefined;
  }

  async getAllTransactions(): Promise<(Transaction & { user: User; package: Package })[]> {
    if (!db) {
      throw new Error('Database not initialized');
    }
    
    const result = await db
      .select({
        id: schema.transactions.id,
        userId: schema.transactions.userId,
        packageId: schema.transactions.packageId,
        paymentId: schema.transactions.paymentId,
        txid: schema.transactions.txid,
        piAmount: schema.transactions.piAmount,
        usdAmount: schema.transactions.usdAmount,
        piPriceAtTime: schema.transactions.piPriceAtTime,
        status: schema.transactions.status,
        failureReason: schema.transactions.failureReason,
        successReason: schema.transactions.successReason,
        gameAccount: schema.transactions.gameAccount,
        metadata: schema.transactions.metadata,
        emailSent: schema.transactions.emailSent,
        createdAt: schema.transactions.createdAt,
        updatedAt: schema.transactions.updatedAt,
      })
      .from(schema.transactions)
      .leftJoin(schema.users, eq(schema.transactions.userId, schema.users.id))
      .leftJoin(schema.packages, eq(schema.transactions.packageId, schema.packages.id));
      
    return result as any;
  }

  async getAdminByUsername(username: string): Promise<Admin | undefined> {
    if (!db) {
      throw new Error('Database not initialized');
    }
    
    const [result] = await db.select().from(schema.admins).where(eq(schema.admins.username, username));
    return result || undefined;
  }

  async createAdmin(insertAdmin: InsertAdmin): Promise<Admin> {
    if (!db) {
      throw new Error('Database not initialized');
    }
    
    const id = randomUUID();
    // @ts-ignore - Drizzle ORM types are complex with JSON fields
    const [result] = await db.insert(schema.admins).values({ 
      id, 
      username: insertAdmin.username,
      password: insertAdmin.password,
      email: insertAdmin.email,
      role: insertAdmin.role ?? 'admin',
      isActive: insertAdmin.isActive ?? true,
      createdAt: new Date(),
      lastLogin: null,
    }).returning();
    return result;
  }

  async getAllActiveAdmins(): Promise<Admin[]> {
    if (!db) {
      throw new Error('Database not initialized');
    }
    
    const result = await db.select().from(schema.admins).where(eq(schema.admins.isActive, true));
    return result;
  }

  async getAdmins(): Promise<Admin[]> {
    if (!db) {
      throw new Error('Database not initialized');
    }
    
    const result = await db.select().from(schema.admins).where(eq(schema.admins.isActive, true));
    return result;
  }

  async getPendingTransactions(): Promise<Transaction[]> {
    if (!db) {
      throw new Error('Database not initialized');
    }
    
    // Get ALL pending transactions (not just recent ones) so we can sync them with Pi Network
    // Transactions that are truly completed/cancelled will be updated by Pi Network sync
    const result = await db
      .select()
      .from(schema.transactions)
      .where(eq(schema.transactions.status, 'pending'))
      .orderBy(desc(schema.transactions.createdAt));
    
    return result;
  }

  async updateAdminLastLogin(id: string): Promise<void> {
    if (isMockDatabase) {
      // Mock implementation - do nothing
      return;
    }
    
    if (!db) {
      throw new Error('Database not initialized');
    }
    
    await db
      .update(schema.admins)
      .set({ lastLogin: new Date() })
      .where(eq(schema.admins.id, id));
  }

  async savePiPrice(price: number): Promise<PiPriceHistory> {
    if (!db) {
      throw new Error('Database not initialized');
    }
    
    const id = randomUUID();
    // @ts-ignore - Drizzle ORM types are complex with JSON fields
    const [result] = await db
      .insert(schema.piPriceHistory)
      .values({ id, price: price.toString() })
      .returning();
    return result;
  }

  async getLatestPiPrice(): Promise<PiPriceHistory | undefined> {
    if (!db) {
      throw new Error('Database not initialized');
    }
    
    const [result] = await db
      .select()
      .from(schema.piPriceHistory)
      .orderBy(desc(schema.piPriceHistory.timestamp))
      .limit(1);
    return result || undefined;
  }

  async getAnalytics(): Promise<{
    totalUsers: number;
    totalTransactions: number;
    totalRevenue: number;
    successRate: number;
    lifetimeLoggedInUsers: number;
  }> {
    if (!db) {
      throw new Error('Database not initialized');
    }
    
    const [userCount] = await db.select({ count: count() }).from(schema.users);
    const [transactionCount] = await db.select({ count: count() }).from(schema.transactions);
    
    const [revenueResult] = await db
      .select({ total: sum(schema.transactions.piAmount) })
      .from(schema.transactions)
      .where(eq(schema.transactions.status, "completed"));
    
    const [completedCount] = await db
      .select({ count: count() })
      .from(schema.transactions)
      .where(eq(schema.transactions.status, "completed"));

    // Count users who have logged in (lastLogin is not null)
    const [loginCount] = await db
      .select({ count: count() })
      .from(schema.users)
      .where(sql`${schema.users.lastLogin} IS NOT NULL`);

    const successRate = transactionCount.count > 0 
      ? (completedCount.count / transactionCount.count) * 100 
      : 0;

    return {
      totalUsers: userCount.count,
      totalTransactions: transactionCount.count,
      totalRevenue: parseFloat(revenueResult?.total || "0"),
      successRate: Math.round(successRate * 100) / 100,
      lifetimeLoggedInUsers: loginCount.count,
    };
  }
  
  // Remove manual referral code generation - let database trigger handle it
  /*
  generateReferralCode(): string {
    // Generate a unique referral code
    return 'REF' + Math.random().toString(36).substring(2, 8).toUpperCase();
  }
  */
  
  async getUserByReferralCode(referralCode: string): Promise<User | undefined> {
    if (!db) {
      throw new Error('Database not initialized');
    }
    
    try {
      // Updated to use the referral_codes table
      const result = await db
        .select({
          user: schema.users
        })
        .from(schema.referralCodes)
        .innerJoin(schema.users, eq(schema.referralCodes.userId, schema.users.id))
        .where(eq(schema.referralCodes.code, referralCode));
      
      return result.length > 0 ? result[0].user : undefined;
    } catch (error) {
      console.error('Error fetching user by referral code:', referralCode, error);
      return undefined;
    }
  }
  
  // Add new method to get user's referral code
  async getUserReferralCode(userId: string): Promise<string | undefined> {
    if (!db) {
      throw new Error('Database not initialized');
    }
    
    try {
      const [result] = await db
        .select({
          code: schema.referralCodes.code
        })
        .from(schema.referralCodes)
        .where(eq(schema.referralCodes.userId, userId));
      
      return result?.code;
    } catch (error) {
      console.error('Error fetching referral code for user:', userId, error);
      return undefined;
    }
  }
  
  // Add new method to reward referrer
  async rewardReferrer(referredUserId: string): Promise<void> {
    if (!db) {
      throw new Error('Database not initialized');
    }
    
    try {
      // First, get the referred user to find who referred them
      const [referredUser] = await db
        .select({
          referredBy: schema.users.referredBy
        })
        .from(schema.users)
        .where(eq(schema.users.id, referredUserId));
      
      if (!referredUser || !referredUser.referredBy) {
        console.log('No referrer found for user', referredUserId);
        return;
      }
      
      // Get the referrer user through the referral code
      const [referrer] = await db
        .select({
          userId: schema.referralCodes.userId
        })
        .from(schema.referralCodes)
        .where(eq(schema.referralCodes.code, referredUser.referredBy));
      
      if (!referrer) {
        console.log('Referrer not found with code', referredUser.referredBy);
        return;
      }

      // Prevent duplicate referral reward processing
      const [existingReward] = await db
        .select({ id: schema.referralRewards.id })
        .from(schema.referralRewards)
        .where(eq(schema.referralRewards.referredUserId, referredUserId));

      if (existingReward) {
        console.log('Referral reward already processed for referred user', referredUserId);
        return;
      }

      const referralRewardTokens = 25;

      // Record the referral reward for analytics and auditing
      await db.insert(schema.referralRewards).values({
        id: randomUUID(),
        referrerId: referrer.userId,
        referredUserId,
        tokensAwarded: referralRewardTokens,
        rewardStatus: 'awarded',
        createdAt: new Date(),
        awardedAt: new Date(),
      });

      // Add B4U Esports Token rewards to both users and keep the ledger in sync.
      await db.update(schema.users)
        .set({ 
          tokens: sql`${schema.users.tokens} + ${referralRewardTokens}`,
          updatedAt: new Date() 
        })
        .where(eq(schema.users.id, referrer.userId));
      await db.insert(schema.tokenTransactions).values({
        userId: referrer.userId,
        amount: referralRewardTokens,
        type: 'referral_reward',
        description: `Referral reward: ${referralRewardTokens} B4U Esports Token`,
        referenceId: referredUserId,
      });

      await db.update(schema.users)
        .set({ 
          tokens: sql`${schema.users.tokens} + ${referralRewardTokens}`,
          updatedAt: new Date() 
        })
        .where(eq(schema.users.id, referredUserId));
      await db.insert(schema.tokenTransactions).values({
        userId: referredUserId,
        amount: referralRewardTokens,
        type: 'referral_reward',
        description: `Referral signup reward: ${referralRewardTokens} B4U Esports Token`,
        referenceId: referrer.userId,
      });

      console.log(`Added ${referralRewardTokens} referral tokens to referrer ${referrer.userId} and referred user ${referredUserId}`);
    } catch (error) {
      console.error('Error rewarding referrer:', error);
      throw error;
    }
  }
  
  async getAllUserEmails(): Promise<string[]> {
    if (isMockDatabase) {
      throw new Error('Mock database is disabled in production');
    }
    
    if (!db) {
      throw new Error('Database not initialized');
    }
    
    try {
      const result = await db.select({ email: schema.users.email }).from(schema.users);
      return result.map(row => row.email).filter(email => email && email.trim() !== '');
    } catch (error) {
      console.error('Error fetching user emails:', error);
      return [];
    }
  }
  
  async updateUserLastLogin(id: string): Promise<void> {
    if (!db) {
      throw new Error('Database not initialized');
    }
    
    try {
      await db
        .update(schema.users)
        .set({ 
          lastLogin: new Date(),
          updatedAt: new Date() 
        })
        .where(eq(schema.users.id, id));
    } catch (error) {
      console.error('Error updating user last login:', error);
      throw error;
    }
  }
  
  async getAllAdminEmails(): Promise<string[]> {
    if (isMockDatabase) {
      throw new Error('Mock database is disabled in production');
    }
    
    if (!db) {
      throw new Error('Database not initialized');
    }
    
    try {
      const result = await db.select({ email: schema.admins.email }).from(schema.admins);
      return result.map(row => row.email).filter(email => email && email.trim() !== '');
    } catch (error) {
      console.error('Error fetching admin emails:', error);
      return [];
    }
  }
  
  // Chat Messages Implementation
  async saveChatMessage(message: any): Promise<any> {
    // Chat feature disabled to reduce Supabase egress and remove persisted chat.
    console.warn('saveChatMessage called but chat feature is disabled. Ignoring message.');
    // Return a mock object to satisfy callers without persisting data.
    return Promise.resolve({
      id: randomUUID(),
      userId: (message as any).userId || null,
      sessionId: (message as any).sessionId || null,
      content: (message as any).content || '',
      createdAt: new Date(),
    } as any);
  }
  
  async getChatMessagesBySession(sessionId: string, limit: number = 50): Promise<any[]> {
    // Chat feature disabled — return empty history to avoid reading large tables.
    console.warn('getChatMessagesBySession called but chat feature is disabled. Returning empty array.');
    return [];
  }
  
  async getUserChatHistory(userId: string, limit: number = 100): Promise<any[]> {
    // Chat feature disabled — return empty history to avoid reading large tables.
    console.warn('getUserChatHistory called but chat feature is disabled. Returning empty array.');
    return [];
  }

  // Tournament implementation
  async getTournaments(status?: string): Promise<Tournament[]> {
    if (!db) {
      throw new Error('Database not initialized');
    }

    const baseQuery = db.select().from(schema.tournaments);
    const query = status
      ? baseQuery.where(eq(schema.tournaments.status, status))
      : baseQuery;

    return await query.orderBy(desc(schema.tournaments.startsAt));
  }

  async getTournament(id: string): Promise<Tournament | undefined> {
    if (!db) {
      throw new Error('Database not initialized');
    }

    const [result] = await db.select().from(schema.tournaments).where(eq(schema.tournaments.id, id));
    return result || undefined;
  }

  async getTournamentBySlug(slug: string): Promise<Tournament | undefined> {
    if (!db) {
      throw new Error('Database not initialized');
    }

    const [result] = await db.select().from(schema.tournaments).where(eq(schema.tournaments.slug, slug));
    return result || undefined;
  }

  async createTournament(tournament: InsertTournament): Promise<Tournament> {
    if (!db) {
      throw new Error('Database not initialized');
    }

    // @ts-ignore - Drizzle ORM types are complex with JSON fields
    const [result] = await db.insert(schema.tournaments).values({
      ...tournament,
      id: randomUUID(),
      createdAt: new Date(),
      updatedAt: new Date(),
    }).returning();
    return result;
  }

  async updateTournament(id: string, tournament: Partial<Tournament>): Promise<Tournament | undefined> {
    if (!db) {
      throw new Error('Database not initialized');
    }

    // @ts-ignore - Drizzle ORM types are complex with JSON fields
    const [result] = await db
      .update(schema.tournaments)
      .set({ ...tournament, updatedAt: new Date() })
      .where(eq(schema.tournaments.id, id))
      .returning();

    return result || undefined;
  }

  async createTournamentPrizeDistribution(prize: InsertTournamentPrizeDistribution): Promise<TournamentPrizeDistribution> {
    if (!db) {
      throw new Error('Database not initialized');
    }

    const [result] = await db.insert(schema.tournamentPrizeDistributions).values({
      ...prize,
      id: randomUUID(),
      createdAt: new Date(),
    }).returning();
    return result;
  }

  async getTournamentPrizeDistributions(tournamentId: string): Promise<TournamentPrizeDistribution[]> {
    if (!db) {
      throw new Error('Database not initialized');
    }

    return await db
      .select()
      .from(schema.tournamentPrizeDistributions)
      .where(eq(schema.tournamentPrizeDistributions.tournamentId, tournamentId))
      .orderBy(schema.tournamentPrizeDistributions.rank);
  }

  async registerForTournament(registration: InsertTournamentRegistration): Promise<TournamentRegistration> {
    if (!db) {
      throw new Error('Database not initialized');
    }

    // @ts-ignore - Drizzle ORM types are complex with JSON fields
    const [result] = await db.insert(schema.tournamentRegistrations).values({
      ...registration,
      id: randomUUID(),
      registeredAt: new Date(),
    }).returning();
    return result;
  }

  async getTournamentRegistrations(tournamentId: string): Promise<TournamentRegistration[]> {
    if (!db) {
      throw new Error('Database not initialized');
    }

    return await db
      .select()
      .from(schema.tournamentRegistrations)
      .where(sql`${schema.tournamentRegistrations.tournamentId}::text = ${tournamentId}::text`)
      .orderBy(desc(schema.tournamentRegistrations.registeredAt));
  }

  async getTournamentRegistrationsLite(tournamentId: string): Promise<Pick<TournamentRegistration, 'id' | 'teamId' | 'status' | 'paymentStatus' | 'metadata'>[]> {
    if (!db) {
      throw new Error('Database not initialized');
    }

    return await db
      .select({
        id: schema.tournamentRegistrations.id,
        teamId: schema.tournamentRegistrations.teamId,
        status: schema.tournamentRegistrations.status,
        paymentStatus: schema.tournamentRegistrations.paymentStatus,
        metadata: schema.tournamentRegistrations.metadata,
      })
      .from(schema.tournamentRegistrations)
      .where(sql`${schema.tournamentRegistrations.tournamentId}::text = ${tournamentId}::text`)
      .orderBy(desc(schema.tournamentRegistrations.registeredAt));
  }

  async getUserTournamentRegistrations(userId: string): Promise<TournamentRegistration[]> {
    if (!db) {
      throw new Error('Database not initialized');
    }

    return await db
      .select()
      .from(schema.tournamentRegistrations)
      .where(sql`${schema.tournamentRegistrations.userId}::text = ${userId}::text`)
      .orderBy(desc(schema.tournamentRegistrations.registeredAt));
  }

  async updateTournamentRegistration(id: string, registration: Partial<TournamentRegistration>): Promise<TournamentRegistration | undefined> {
    if (!db) {
      throw new Error('Database not initialized');
    }

    // @ts-ignore - Drizzle ORM types are complex with JSON fields
    const [result] = await db
      .update(schema.tournamentRegistrations)
      .set(registration)
      .where(eq(schema.tournamentRegistrations.id, id))
      .returning();

    return result || undefined;
  }

  async getTournamentRegistrationByPaymentId(paymentId: string): Promise<TournamentRegistration | undefined> {
    if (!db) {
      throw new Error('Database not initialized');
    }

    const [result] = await db
      .select()
      .from(schema.tournamentRegistrations)
      .where(eq(schema.tournamentRegistrations.paymentId, paymentId));

    return result || undefined;
  }

  async createTournamentTeam(team: InsertTournamentTeam): Promise<TournamentTeam> {
    if (!db) {
      throw new Error('Database not initialized');
    }

    const teamId = randomUUID();
    const inviteCode = team.inviteCode || `TEAM-${randomUUID().slice(0, 8).toUpperCase()}`;

    // @ts-ignore - Drizzle ORM types are complex with JSON fields
    const [result] = await db.insert(schema.tournamentTeams).values({
      ...team,
      id: teamId,
      inviteCode,
      createdAt: new Date(),
      updatedAt: new Date(),
    }).returning();

    await this.addTournamentTeamMember(teamId, team.captainUserId, 'captain');
    return result;
  }

  async addTournamentTeamMember(teamId: string, userId: string, role: string = 'member'): Promise<TournamentTeamMember> {
    if (!db) {
      throw new Error('Database not initialized');
    }

    const [result] = await db.insert(schema.tournamentTeamMembers).values({
      id: randomUUID(),
      teamId,
      userId,
      role,
      status: 'active',
      joinedAt: new Date(),
    }).returning();
    return result;
  }

  async addTournamentTeamMemberAdvanced(memberData: { teamId: string; userId?: string; role?: string; status?: string }): Promise<TournamentTeamMember> {
    if (!db) {
      throw new Error('Database not initialized');
    }
    if (!memberData.userId) {
      throw new Error('userId is required to add a tournament team member');
    }

    const [result] = await db.insert(schema.tournamentTeamMembers).values({
      id: randomUUID(),
      teamId: memberData.teamId,
      userId: memberData.userId,
      role: memberData.role || 'member',
      status: memberData.status || 'active',
      joinedAt: new Date(),
    }).returning();
    return result;
  }

  async getTournamentTeamMembers(teamId: string): Promise<TournamentTeamMember[]> {
    if (!db) {
      throw new Error('Database not initialized');
    }

    return await db
      .select()
      .from(schema.tournamentTeamMembers)
      .where(sql`${schema.tournamentTeamMembers.teamId}::text = ${teamId}::text`)
      .orderBy(schema.tournamentTeamMembers.joinedAt);
  }

  async getTournamentRegistrationByTeam(teamId: string): Promise<TournamentRegistration | undefined> {
    if (!db) {
      throw new Error('Database not initialized');
    }

    const [result] = await db
      .select()
      .from(schema.tournamentRegistrations)
      .where(sql`${schema.tournamentRegistrations.teamId}::text = ${teamId}::text`);

    return result || undefined;
  }

  async createTournamentRegistration(registration: InsertTournamentRegistration): Promise<TournamentRegistration> {
    if (!db) {
      throw new Error('Database not initialized');
    }

    // @ts-ignore - Drizzle ORM types are complex with JSON fields
    const [result] = await db.insert(schema.tournamentRegistrations).values({
      ...registration,
      id: randomUUID(),
      registeredAt: new Date(),
    }).returning();
    return result;
  }

  async createTournamentLobby(lobbyData: { tournamentId: string; matchId?: string; name: string; mapName?: string; roomCode?: string; roomPassword?: string; status?: string; capacity?: number }): Promise<any> {
    if (!db) {
      throw new Error('Database not initialized');
    }

    const [result] = await db.insert(schema.tournamentLobbies).values({
      id: randomUUID(),
      tournamentId: lobbyData.tournamentId,
      matchId: lobbyData.matchId || null,
      name: lobbyData.name,
      mapName: lobbyData.mapName || null,
      roomCode: lobbyData.roomCode || null,
      roomPassword: lobbyData.roomPassword || null,
      status: lobbyData.status || 'waiting',
      capacity: lobbyData.capacity || 100,
      createdAt: new Date(),
      updatedAt: new Date(),
    }).returning();
    return result;
  }

  async updateTournamentLobby(lobbyId: string, updateData: Record<string, any>): Promise<any> {
    if (!db) {
      throw new Error('Database not initialized');
    }

    const [result] = await db
      .update(schema.tournamentLobbies)
      .set({ ...updateData, updatedAt: new Date() })
      .where(eq(schema.tournamentLobbies.id, lobbyId))
      .returning();

    return result || undefined;
  }

  async deleteTournamentLobby(lobbyId: string): Promise<any> {
    if (!db) {
      throw new Error('Database not initialized');
    }

    const [result] = await db
      .delete(schema.tournamentLobbies)
      .where(eq(schema.tournamentLobbies.id, lobbyId))
      .returning();

    return result || undefined;
  }

  async deleteTournamentLeaderboard(tournamentId: string): Promise<void> {
    if (!db) throw new Error('Database not initialized');
    await db.execute(sql`DELETE FROM tournament_leaderboards WHERE tournament_id = ${tournamentId}`);
  }

  async deleteTournamentMatchResults_byTournament(tournamentId: string): Promise<void> {
    if (!db) throw new Error('Database not initialized');
    await db.execute(sql`
      DELETE FROM tournament_match_results
      WHERE match_id IN (
        SELECT id FROM tournament_matches WHERE tournament_id = ${tournamentId}
      )
    `);
  }

  async deleteTournament(tournamentId: string): Promise<void> {
    if (!db) throw new Error('Database not initialized');
    // Delete registrations, teams, payments first (FK order)
    await db.execute(sql`DELETE FROM tournament_registrations WHERE tournament_id = ${tournamentId}`).catch(() => {});
    await db.execute(sql`DELETE FROM tournament_teams WHERE tournament_id = ${tournamentId}`).catch(() => {});
    await db.execute(sql`DELETE FROM tournament_prize_distributions WHERE tournament_id = ${tournamentId}`).catch(() => {});
    await db.execute(sql`DELETE FROM tournament_scoring_rules WHERE tournament_id = ${tournamentId}`).catch(() => {});
    await db.execute(sql`DELETE FROM tournament_lobbies WHERE tournament_id = ${tournamentId}`).catch(() => {});
    await db.execute(sql`DELETE FROM tournaments WHERE id = ${tournamentId}`);
  }

  async getTournamentLobbies(tournamentId: string): Promise<any[]> {
    if (!db) {
      throw new Error('Database not initialized');
    }

    return await db
      .select()
      .from(schema.tournamentLobbies)
      .where(eq(schema.tournamentLobbies.tournamentId, tournamentId))
      .orderBy(schema.tournamentLobbies.createdAt);
  }

  async getTournamentMatch(matchId: string): Promise<TournamentMatch | undefined> {
    if (!db) {
      throw new Error('Database not initialized');
    }

    const [result] = await db
      .select()
      .from(schema.tournamentMatches)
      .where(eq(schema.tournamentMatches.id, matchId));

    return result || undefined;
  }

  async getTournamentMatchResults(matchId: string): Promise<TournamentMatchResult[]> {
    if (!db) {
      throw new Error('Database not initialized');
    }

    return await db
      .select()
      .from(schema.tournamentMatchResults)
      .where(eq(schema.tournamentMatchResults.matchId, matchId))
      .orderBy(schema.tournamentMatchResults.placement);
  }

  async createTournamentMatchResult(resultData: InsertTournamentMatchResult): Promise<TournamentMatchResult> {
    if (!db) {
      throw new Error('Database not initialized');
    }

    // @ts-ignore - Drizzle ORM types are complex with JSON fields
    const [result] = await db.insert(schema.tournamentMatchResults).values({
      ...resultData,
      id: randomUUID(),
      createdAt: new Date(),
    }).returning();
    return result;
  }

  async deleteTournamentMatchResults(matchId: string): Promise<void> {
    if (!db) {
      throw new Error('Database not initialized');
    }

    await db.delete(schema.tournamentMatchResults).where(eq(schema.tournamentMatchResults.matchId, matchId));
  }

  async rebuildTournamentLeaderboard(tournamentId: string): Promise<TournamentLeaderboard[]> {
    if (!db) {
      throw new Error('Database not initialized');
    }

    await db.execute(sql`DELETE FROM tournament_leaderboards WHERE tournament_id = ${tournamentId}`);

    await db.execute(sql`
      WITH leaderboard_rows AS (
        SELECT
          mr.team_id AS team_id,
          RANK() OVER (
            ORDER BY SUM(mr.points_awarded) DESC,
                     SUM(mr.kills) DESC,
                     SUM(CASE WHEN mr.placement = 1 THEN 1 ELSE 0 END) DESC
          ) AS rank,
          SUM(mr.points_awarded) AS total_points,
          SUM(mr.kills) AS total_kills,
          COUNT(*) AS matches_played,
          SUM(CASE WHEN mr.wwcd > 0 THEN 1 ELSE 0 END) AS wwcd_count,
          SUM(CASE WHEN mr.placement = 1 THEN 1 ELSE 0 END) AS wins,
          SUM(COALESCE(mr.prize_pi, '0')) AS prize_sum
        FROM tournament_match_results mr
        JOIN tournament_matches m ON m.id = mr.match_id AND m.tournament_id = ${tournamentId}
        WHERE mr.team_id IS NOT NULL
        GROUP BY mr.team_id
      )
      INSERT INTO tournament_leaderboards (
        id, tournament_id, team_id, rank, total_points, total_kills, matches_played, wwcd_count, wins, prize_pi, prize_status, updated_at
      )
      SELECT
        gen_random_uuid(),
        ${tournamentId},
        lr.team_id,
        lr.rank,
        lr.total_points,
        lr.total_kills,
        lr.matches_played,
        lr.wwcd_count,
        lr.wins,
        COALESCE(lr.prize_sum, pd.prize_pi, '0'),
        CASE WHEN COALESCE(lr.prize_sum, pd.prize_pi, '0')::decimal > 0 THEN 'pending' ELSE 'not_awarded' END,
        now()
      FROM leaderboard_rows lr
      LEFT JOIN tournament_prize_distributions pd
        ON pd.tournament_id = ${tournamentId} AND pd.rank = lr.rank
      ORDER BY lr.rank;
    `);

    return this.getTournamentLeaderboard(tournamentId);
  }

  async getTournamentTeams(tournamentId: string): Promise<TournamentTeam[]> {
    if (!db) {
      throw new Error('Database not initialized');
    }

    return await db
      .select()
      .from(schema.tournamentTeams)
      .where(sql`${schema.tournamentTeams.tournamentId}::text = ${tournamentId}::text`)
      .orderBy(schema.tournamentTeams.seed, schema.tournamentTeams.createdAt);
  }

  async checkInTournamentParticipant(tournamentId: string, userId: string, teamId?: string): Promise<TournamentCheckIn> {
    if (!db) {
      throw new Error('Database not initialized');
    }

    const [result] = await db.insert(schema.tournamentCheckIns).values({
      id: randomUUID(),
      tournamentId,
      userId,
      teamId: teamId ?? null,
      status: 'checked_in',
      checkedInAt: new Date(),
    }).returning();
    return result;
  }

  async createTournamentPayment(payment: InsertTournamentPayment): Promise<TournamentPayment> {
    if (!db) {
      throw new Error('Database not initialized');
    }

    // @ts-ignore - Drizzle ORM types are complex with JSON fields
    const [result] = await db.insert(schema.tournamentPayments).values({
      ...payment,
      id: randomUUID(),
      createdAt: new Date(),
      updatedAt: new Date(),
    }).returning();
    return result;
  }

  async updateTournamentPayment(id: string, payment: Partial<TournamentPayment>): Promise<TournamentPayment | undefined> {
    if (!db) {
      throw new Error('Database not initialized');
    }

    // @ts-ignore - Drizzle ORM types are complex with JSON fields
    const [result] = await db
      .update(schema.tournamentPayments)
      .set({ ...payment, updatedAt: new Date() })
      .where(eq(schema.tournamentPayments.id, id))
      .returning();

    return result || undefined;
  }

  async createTournamentMatch(match: InsertTournamentMatch): Promise<TournamentMatch> {
    if (!db) {
      throw new Error('Database not initialized');
    }

    // @ts-ignore - Drizzle ORM types are complex with JSON fields
    const [result] = await db.insert(schema.tournamentMatches).values({
      ...match,
      id: randomUUID(),
      createdAt: new Date(),
      updatedAt: new Date(),
    }).returning();
    return result;
  }

  async updateTournamentMatch(id: string, match: Partial<TournamentMatch>): Promise<TournamentMatch | undefined> {
    if (!db) {
      throw new Error('Database not initialized');
    }

    // @ts-ignore - Drizzle ORM types are complex with JSON fields
    const [result] = await db
      .update(schema.tournamentMatches)
      .set({ ...match, updatedAt: new Date() })
      .where(eq(schema.tournamentMatches.id, id))
      .returning();

    return result || undefined;
  }

  async deleteTournamentMatch(id: string): Promise<TournamentMatch | undefined> {
    if (!db) {
      throw new Error('Database not initialized');
    }

    const [result] = await db
      .delete(schema.tournamentMatches)
      .where(eq(schema.tournamentMatches.id, id))
      .returning();

    return result || undefined;
  }

  async addTournamentMatchParticipant(participant: InsertTournamentMatchParticipant): Promise<TournamentMatchParticipant> {
    if (!db) {
      throw new Error('Database not initialized');
    }

    // @ts-ignore - Drizzle ORM types are complex with JSON fields
    const [result] = await db.insert(schema.tournamentMatchParticipants).values({
      ...participant,
      id: randomUUID(),
    }).returning();
    return result;
  }

  async submitTournamentMatchResult(resultData: InsertTournamentMatchResult): Promise<TournamentMatchResult> {
    if (!db) {
      throw new Error('Database not initialized');
    }

    // @ts-ignore - Drizzle ORM types are complex with JSON fields
    const [result] = await db.insert(schema.tournamentMatchResults).values({
      ...resultData,
      id: randomUUID(),
      createdAt: new Date(),
    }).returning();
    return result;
  }

  async getTournamentMatches(tournamentId: string): Promise<TournamentMatch[]> {
    if (!db) {
      throw new Error('Database not initialized');
    }

    return await db
      .select()
      .from(schema.tournamentMatches)
      .where(eq(schema.tournamentMatches.tournamentId, tournamentId))
      .orderBy(schema.tournamentMatches.round, schema.tournamentMatches.matchNumber);
  }

  async upsertTournamentLeaderboardEntry(entry: InsertTournamentLeaderboard): Promise<TournamentLeaderboard> {
    if (!db) {
      throw new Error('Database not initialized');
    }

    // @ts-ignore - Drizzle ORM types are complex with JSON fields
    const [result] = await db.insert(schema.tournamentLeaderboards).values({
      ...entry,
      id: randomUUID(),
      updatedAt: new Date(),
    }).onConflictDoUpdate({
      target: [schema.tournamentLeaderboards.tournamentId, schema.tournamentLeaderboards.rank],
      set: {
        userId: entry.userId ?? null,
        teamId: entry.teamId ?? null,
        totalPoints: entry.totalPoints ?? 0,
        totalKills: entry.totalKills ?? 0,
        matchesPlayed: entry.matchesPlayed ?? 0,
        wins: entry.wins ?? 0,
        prizePi: entry.prizePi ?? "0",
        prizeStatus: entry.prizeStatus ?? "not_awarded",
        updatedAt: new Date(),
      },
    }).returning();
    return result;
  }

  async getTournamentLeaderboard(tournamentId: string): Promise<TournamentLeaderboard[]> {
    if (!db) {
      throw new Error('Database not initialized');
    }

    return await db
      .select()
      .from(schema.tournamentLeaderboards)
      .where(eq(schema.tournamentLeaderboards.tournamentId, tournamentId))
      .orderBy(schema.tournamentLeaderboards.rank);
  }

  async createTournamentNotification(notification: InsertTournamentNotification): Promise<TournamentNotification> {
    if (!db) {
      throw new Error('Database not initialized');
    }

    // @ts-ignore - Drizzle ORM types are complex with JSON fields
    const [result] = await db.insert(schema.tournamentNotifications).values({
      ...notification,
      id: randomUUID(),
      createdAt: new Date(),
    }).returning();
    return result;
  }

  async getUserTournamentNotifications(userId: string): Promise<TournamentNotification[]> {
    if (!db) {
      throw new Error('Database not initialized');
    }

    return await db
      .select()
      .from(schema.tournamentNotifications)
      .where(eq(schema.tournamentNotifications.userId, userId))
      .orderBy(desc(schema.tournamentNotifications.createdAt));
  }
}

export const storage = new DatabaseStorage();
